### ISSUE TITLE
Please Give example how to export jpg image 

### ISSUE THREAD

**Issue by Kevin301099** [qdwang/quickraw#2]

**Comment by qdwang** [comment]
For `v0.1.6` you can use `save_with_quality` method here: https://github.com/RawLabo/quickraw/blob/v0.1.6/src/export.rs#L120C12-L120C29 . Notice that you need to compile with the `image` feature.

But for `main` and `dev` nightly version, there are no built-in JPG export method yet. You can use the `image` crate to do the job manually.
